#' Methods-section paragraph from a symbolized model
#'
#' @description
#' Returns a draft Methods-section paragraph for a fitted model — the kind
#' of paragraph a biologist would otherwise have to write by hand into a
#' paper. The prose is composed from a CSV template
#' (`inst/extdata/methods-templates.csv`) using slots filled from the
#' `symbolized_model`. No prose is generated by a language model at
#' runtime; every phrase traces to the template row plus the substituted
#' slots.
#'
#' The output is always a **draft**. Treat it as starting material to be
#' edited: confirm the package version, soften or sharpen the sentences,
#' add the citation, and drop in any study-specific context. The print
#' method appends an editorial reminder for that reason.
#'
#' @param sym A [`symbolized_model`][new_symbolized_model].
#' @param ... Reserved for future use.
#'
#' @return A list classed `c("symbolizer_methods_text", "list")` with
#'   slots `text` (the assembled paragraph as a single character string),
#'   `slots` (the named substitutions used), and `reminders` (character
#'   vector of editorial reminders for the author).
#'
#' @examples
#' \dontrun{
#' fit <- drmTMB::drmTMB(
#'   drmTMB::drm_formula(body_mass ~ temperature, sigma ~ temperature),
#'   family = stats::gaussian(), data = body_mass_dat
#' )
#' sym <- symbolize(fit)
#' methods_text(sym)
#' }
#'
#' @export
methods_text <- function(sym, ...) {
  UseMethod("methods_text")
}

#' @export
methods_text.default <- function(sym, ...) {
  cli::cli_abort(c(
    "{.fn methods_text} has no method for objects of class {.cls {class(sym)[1L]}}.",
    i = "Pass the output of {.fn symbolize}."
  ))
}

#' @export
methods_text.symbolized_model <- function(sym, ...) {
  cls    <- sym$model$class    %||% NA_character_
  family <- sym$model$family   %||% NA_character_
  tmpl   <- methods_template_for(cls, family)
  slots  <- methods_slots_for(sym)
  text   <- methods_substitute(tmpl, slots)
  out <- list(
    text      = text,
    slots     = slots,
    reminders = methods_reminders_for(sym, slots)
  )
  class(out) <- c("symbolizer_methods_text", "list")
  out
}

# -- internal helpers --------------------------------------------------------

# Look up the row in methods-templates.csv that matches (class, family).
# Errors with a friendly message if none exists yet.
methods_template_for <- function(cls, family) {
  tbl <- load_template("methods-templates")
  hit <- tbl[tbl$class == cls & tbl$family == family, , drop = FALSE]
  if (nrow(hit) == 0L) {
    # Build the list of supported combos from the CSV itself so the
    # message never drifts out of sync with reality.
    combos <- sprintf("%s / %s", tbl$class, tbl$family)
    combos_chr <- paste(sort(unique(combos)), collapse = ", ")
    cli::cli_abort(c(
      "No {.fn methods_text} template for class {.val {cls}} / family {.val {family}}.",
      i = "Templates ship today for: {combos_chr}.",
      i = "Open an issue if you need a different combination."
    ))
  }
  hit$template[[1L]]
}

# Build the slot list once. Every {placeholder} in the template must
# resolve to a key here.
methods_slots_for <- function(sym) {
  cls    <- sym$model$class    %||% NA_character_
  family <- sym$model$family   %||% NA_character_
  pkg    <- sym$model$package  %||% cls
  n_obs  <- sym$model$n_obs    %||% NA_integer_
  # ci_method is stored lowercase ("wald" / "profile") on metadata; capitalise
  # the first letter so the rendered sentence reads "95% Wald confidence
  # intervals" rather than "95% wald confidence intervals".
  ci_raw  <- sym$metadata$ci_method %||% "wald"
  ci_meth <- paste0(toupper(substr(ci_raw, 1L, 1L)),
                    substr(ci_raw, 2L, nchar(ci_raw)))
  pkg_version <- methods_pkg_version(pkg)

  slots <- list(
    package         = pkg,
    package_version = pkg_version,
    n_obs           = format(n_obs),
    ci_method       = ci_meth,
    re_clause       = methods_re_clause(sym)
  )

  # Univariate drmTMB families share a slot shape: a single response, a mu
  # submodel, and a sigma submodel (Student-t adds nu; Poisson would skip
  # sigma; etc.). Rather than branching per family, fill the common slots
  # and add family-specific extras after.
  # Note: "Gamma" is capitalised because base R's stats::Gamma() registers
  # the family string as "Gamma" on the fit; the other names are lowercase
  # as drmTMB's own family() functions write them.
  univariate_drm_families <- c(
    "gaussian", "student", "lognormal", "Gamma", "beta",
    "poisson", "nbinom2", "beta_binomial", "truncated_nbinom2",
    "cumulative_logit"
  )
  if (identical(cls, "drmTMB") && family %in% univariate_drm_families) {
    slots$response             <- sym$model$response %||% "the response"
    slots$response_units_clause <- methods_units_clause(sym, slots$response)
    slots$mu_predictors_clause    <- methods_predictors_clause(sym, "mu")
    # Sigma submodel: exists for every current univariate family except
    # Poisson. Fill it when the submodel is present in the fit.
    if ("sigma" %in% sym$submodels$parameter) {
      slots$sigma_predictors_clause <- methods_predictors_clause(sym, "sigma")
    }
    # Student-t-specific extra slot for the nu submodel.
    if (identical(family, "student")) {
      slots$nu_predictors_clause <- methods_predictors_clause(sym, "nu")
    }
    # Optional zero-inflation / hurdle clauses (Poisson / nbinom2 only).
    # The template carries {zi_extra_clause} / {hu_extra_clause} placeholders
    # that default to empty when the corresponding submodel is absent.
    slots$zi_extra_clause <- if ("zi" %in% sym$submodels$parameter) {
      sprintf(
        " A zero-inflation component modelled the probability of a structural zero on the logit scale as a function of %s; the conditional distribution is a mixture P(Y=0) = pi_zi + (1 - pi_zi) * f(0 | mu, ...).",
        methods_predictors_clause(sym, "zi")
      )
    } else ""
    slots$hu_extra_clause <- if ("hu" %in% sym$submodels$parameter) {
      sprintf(
        " A hurdle component modelled the probability of a zero on the logit scale as a function of %s; positives were drawn from the zero-truncated form of the count distribution.",
        methods_predictors_clause(sym, "hu")
      )
    } else ""
  } else if (identical(family, "biv_gaussian") && identical(cls, "drmTMB")) {
    responses <- sym$model$responses %||%
                 strsplit(sym$model$response %||% ", ",
                          ",\\s*")[[1L]]
    slots$response_1 <- responses[[1L]] %||% "response 1"
    slots$response_2 <- if (length(responses) >= 2L) responses[[2L]] else "response 2"
    slots$response_units_clause <-
      methods_units_clause_biv(sym, slots$response_1, slots$response_2)
    s1 <- methods_predictors_clause(sym, "sigma1")
    s2 <- methods_predictors_clause(sym, "sigma2")
    rh <- methods_predictors_clause(sym, "rho12")
    slots$mu1_predictors_clause    <- methods_predictors_clause(sym, "mu1")
    slots$mu2_predictors_clause    <- methods_predictors_clause(sym, "mu2")
    slots$sigma1_predictors_clause <- s1
    slots$sigma2_predictors_clause <- s2
    slots$rho12_predictors_clause  <- rh
    # Pre-baked phrasing that reads cleanly when the per-submodel clauses
    # collapse to "an intercept only". Used by the biv_gaussian template
    # in place of bare `({s1}; {s2})` parens.
    slots$sigma_pair_clause <- methods_sigma_pair_phrasing(s1, s2)
    slots$rho12_clause      <- methods_rho12_phrasing(rh)
  } else if (identical(family, "gaussian") && identical(cls, "gllvmTMB")) {
    nt <- nrow(sym$loadings) %||% NA_integer_
    nl <- if (!is.null(sym$loadings$axis)) {
      length(unique(sym$loadings$axis))
    } else NA_integer_
    nu <- sym$model$n_units %||% NA_integer_
    slots$n_traits   <- format(nt)
    slots$n_latents  <- format(nl)
    slots$n_units    <- format(nu)
    slots$unit_word  <- "unit"
    slots$axes_word  <- if (identical(nl, 1L)) "axis" else "axes"
  } else if (identical(family, "gaussian") && identical(cls, "glmmTMB")) {
    slots$response             <- sym$model$response %||% "the response"
    slots$response_units_clause <- methods_units_clause(sym, slots$response)
    slots$mu_predictors_clause    <- methods_predictors_clause(sym, "mu")
    # The sigma submodel is present only when the user fit
    # dispformula = ~ z. When absent, drop the sentence entirely.
    slots$sigma_extra_clause <- if ("sigma" %in% sym$submodels$parameter) {
      sprintf(
        " The residual standard deviation was modelled on the log scale as a function of %s.",
        methods_predictors_clause(sym, "sigma")
      )
    } else ""
  } else if (identical(family, "gaussian") && identical(cls, "brmsfit")) {
    slots$response             <- sym$model$response %||% "the response"
    slots$response_units_clause <- methods_units_clause(sym, slots$response)
    slots$mu_predictors_clause    <- methods_predictors_clause(sym, "mu")
    # brms templates don't carry {ci_method}; the band is always
    # credible. Strip it so leftover placeholders aren't flagged.
    slots$ci_method <- NULL
  } else if (identical(family, "gaussian") && identical(cls, "MCMCglmm")) {
    slots$response             <- sym$model$response %||% "the response"
    slots$response_units_clause <- methods_units_clause(sym, slots$response)
    slots$mu_predictors_clause    <- methods_predictors_clause(sym, "mu")
    slots$ci_method <- NULL
  }

  slots
}

# Format a comma-and-and-separated list of predictor names for one
# submodel, or "an intercept only" when only the intercept is present.
methods_predictors_clause <- function(sym, submodel) {
  trms <- sym$terms
  if (is.null(trms) || nrow(trms) == 0L) return("an intercept only")
  sel <- trms$submodel == submodel & trms$role != "intercept"
  if (!any(sel)) return("an intercept only")
  preds <- unique(trms$variable[sel])
  preds <- preds[!is.na(preds) & nzchar(preds)]
  if (length(preds) == 0L) return("an intercept only")
  methods_oxford_list(preds)
}

# Build the units clause: " (units: g)" / " (units: g, C)" etc., or "" if
# none of the variables involved have units.
methods_units_clause <- function(sym, response) {
  d <- sym$symbol_dictionary
  if (is.null(d) || nrow(d) == 0L) return("")
  hit <- d$units[!is.na(d$variable) & d$variable == response]
  hit <- hit[!is.na(hit) & nzchar(hit)]
  if (length(hit) == 0L) return("")
  paste0(" (units: ", hit[[1L]], ")")
}

# Build the biv_gaussian "sigma pair" prose. The default per-submodel clause
# `an intercept only` reads badly when concatenated with a semicolon inside
# parentheses (e.g., `(an intercept only; an intercept only)`). This helper
# picks a phrase that flows in three cases:
#
#   both intercept-only           -> "both intercept-only"
#   one intercept-only, one not   -> "<response 1> intercept-only; <response 2>
#                                     as a function of `x`"
#   both have predictors          -> "<response 1>: a function of `x1`;
#                                     <response 2>: a function of `x2`"
#
# Used by the biv_gaussian methods-template via the {sigma_pair_clause} slot.
methods_sigma_pair_phrasing <- function(s1, s2) {
  io1 <- identical(s1, "an intercept only")
  io2 <- identical(s2, "an intercept only")
  if (io1 && io2) return("both intercept-only")
  if (io1 && !io2)  return(sprintf("the first scale intercept-only, the second a function of %s", s2))
  if (!io1 && io2)  return(sprintf("the first scale a function of %s, the second intercept-only", s1))
  sprintf("the first scale a function of %s, the second a function of %s", s1, s2)
}

methods_rho12_phrasing <- function(rh) {
  if (identical(rh, "an intercept only")) {
    "with an intercept only on the Fisher-z linear predictor"
  } else {
    sprintf("as a function of %s on the Fisher-z linear predictor", rh)
  }
}

methods_units_clause_biv <- function(sym, r1, r2) {
  d <- sym$symbol_dictionary
  if (is.null(d) || nrow(d) == 0L) return("")
  unit_for <- function(var) {
    hit <- d$units[!is.na(d$variable) & d$variable == var]
    hit <- hit[!is.na(hit) & nzchar(hit)]
    if (length(hit) == 0L) NA_character_ else hit[[1L]]
  }
  u1 <- unit_for(r1); u2 <- unit_for(r2)
  if (is.na(u1) && is.na(u2)) return("")
  if (is.na(u1) || is.na(u2)) {
    return(paste0(" (units: ", u1 %||% u2, ")"))
  }
  paste0(" (units: ", u1, " and ", u2, " respectively)")
}

# Random-effect clause: includes its own leading space + final period
# when present, or "" when no random effects in the fit.
methods_re_clause <- function(sym) {
  re <- sym$random_effects
  if (is.null(re) || nrow(re) == 0L) return("")
  # The extractor names this column `group_var` (the grouping variable
  # in the R formula), not `group`.
  col <- if ("group_var" %in% names(re)) "group_var" else
         if ("group" %in% names(re)) "group" else NA_character_
  if (is.na(col)) return("")
  groups <- unique(re[[col]][!is.na(re[[col]]) & nzchar(re[[col]])])
  if (length(groups) == 0L) return("")

  # If the random_effects tibble lacks a `component` column (e.g. an older
  # extractor or a different model class), fall back to the historic
  # intercept-only wording.
  has_component <- "component" %in% names(re)
  if (!has_component) {
    return(paste0(" A random intercept was included for ",
                  methods_oxford_list(groups), "."))
  }

  # Per-group description. Each group can have a random intercept, random
  # slope(s), or both.
  per_group <- vapply(groups, function(gv) {
    sel <- re[[col]] == gv
    comps <- re$component[sel]
    has_int <- "(Intercept)" %in% comps
    slopes  <- comps[comps != "(Intercept)" & !is.na(comps)]
    if (length(slopes) == 0L && has_int) {
      sprintf("a random intercept for `%s`", gv)
    } else if (length(slopes) >= 1L && has_int) {
      slope_part <- if (length(slopes) == 1L) {
        sprintf("a random slope on `%s`", slopes[[1L]])
      } else {
        sprintf("random slopes on %s", methods_oxford_list(slopes))
      }
      sprintf("a random intercept and %s for `%s`", slope_part, gv)
    } else if (length(slopes) >= 1L) {
      slope_part <- if (length(slopes) == 1L) {
        sprintf("a random slope on `%s`", slopes[[1L]])
      } else {
        sprintf("random slopes on %s", methods_oxford_list(slopes))
      }
      sprintf("%s for `%s`", slope_part, gv)
    } else ""
  }, character(1L))
  per_group <- per_group[nzchar(per_group)]
  if (length(per_group) == 0L) return("")

  # Capitalize the first letter of the first clause; join multi-group
  # descriptions with semicolons. Verb agreement: singular "was" when
  # there's just one group with just one component; plural "were"
  # otherwise.
  per_group[[1L]] <- paste0(toupper(substring(per_group[[1L]], 1L, 1L)),
                            substring(per_group[[1L]], 2L))
  joined <- paste(per_group, collapse = "; ")
  total_components <- nrow(re)
  verb <- if (total_components == 1L) "was" else "were"
  paste0(" ", joined, " ", verb, " included in the model.")
}

# Oxford-comma list: c("a") -> "a"; c("a","b") -> "a and b"; c("a","b","c")
# -> "a, b, and c". Surrounds each element in backticks for readability.
methods_oxford_list <- function(xs) {
  xs <- as.character(xs)
  xs <- xs[!is.na(xs) & nzchar(xs)]
  if (length(xs) == 0L) return("")
  bk <- paste0("`", xs, "`")
  if (length(bk) == 1L) return(bk)
  if (length(bk) == 2L) return(paste(bk, collapse = " and "))
  paste0(paste(bk[-length(bk)], collapse = ", "),
         ", and ", bk[[length(bk)]])
}

# Substitute {slot} placeholders in a template with their values.
# Leaves any {slot} that has no value as a literal warning marker
# so the author notices instead of seeing a silent omission.
methods_substitute <- function(template, slots) {
  out <- template
  for (nm in names(slots)) {
    out <- gsub(paste0("\\{", nm, "\\}"), slots[[nm]], out, fixed = FALSE)
  }
  # Detect any remaining {unfilled} placeholders.
  remaining <- regmatches(out, gregexpr("\\{[A-Za-z_][A-Za-z0-9_]*\\}", out))[[1L]]
  if (length(remaining) > 0L) {
    out <- gsub("\\{([A-Za-z_][A-Za-z0-9_]*)\\}", "[unfilled: \\1]", out)
  }
  out
}

# Editorial reminders appended to the print method.
methods_reminders_for <- function(sym, slots) {
  msgs <- c(
    "This is a draft. Confirm every claim against your fit before pasting.",
    sprintf("Package version `%s` was read from the local install; verify it matches what you actually fit with.",
            slots$package_version %||% "??")
  )
  if (!is.null(sym$random_effects) && nrow(sym$random_effects) > 0L) {
    msgs <- c(msgs,
      "Random-effect structure described here; if you used a more complex RE structure (random slopes, nested, crossed), reword that sentence.")
  }
  msgs
}

# Best-effort package version lookup. Falls back to "??" when the package
# is not installed (e.g., when running tests in an isolated lib path).
methods_pkg_version <- function(pkg) {
  if (!nzchar(pkg)) return("??")
  v <- tryCatch(
    as.character(utils::packageVersion(pkg)),
    error = function(e) "??"
  )
  v
}

# -- print + knit_print -----------------------------------------------------

#' @export
print.symbolizer_methods_text <- function(x, ...) {
  cli::cli_h2("Methods text (draft)")
  cli::cli_text(x$text)
  if (length(x$reminders) > 0L) {
    cli::cli_h3("Reminders before you paste")
    for (r in x$reminders) cli::cli_text("* {r}")
  }
  invisible(x)
}

#' @exportS3Method knitr::knit_print
knit_print.symbolizer_methods_text <- function(x, ...) {
  out <- paste(
    c("",
      x$text,
      "",
      "*Reminders:*",
      "",
      paste0("- ", x$reminders),
      ""),
    collapse = "\n"
  )
  knitr::asis_output(out)
}
